FROM node:10-buster

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN set -x; \
    groupmod -g $GROUP_ID node && \
    usermod -u $USER_ID node

USER node
WORKDIR /code

COPY entrypoint-frontend.sh /
ENTRYPOINT [ "/entrypoint-frontend.sh" ]
