FROM node:20-bookworm

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN usermod -u $USER_ID node && \
  groupmod -g $GROUP_ID node

USER node
WORKDIR /code

COPY entrypoint-frontend.sh /
ENTRYPOINT [ "/entrypoint-frontend.sh" ]
