{% raw %}
---
- hosts: all
  vars_files:
   - parameters.yml
  become: no

  pre_tasks:
    - name: delete existing database
      postgresql_db: name={{ database_name }}
                     owner={{ database_user }}
                     state=absent
      become_user: postgres
      become: yes
      ignore_errors: yes

  roles:
    - { role: base }
    - { role: postgresql }
    - { role: django }
{% endraw %}
